### ISSUE TITLE
Непонятная область для ввода 

### ISSUE THREAD

**Issue by vallerili** [wmaksimova/new_planner#3]
1) Открываю приложение
2) Вижу маленький курсор в самом низу, над словами "Твоя мотивация на день"
![image](https://user-images.githubusercontent.com/113391020/205454475-41438f86-980e-4750-85f6-94d1451ae2d0.png)

3) Могу написать там что-то 
![image](https://user-images.githubusercontent.com/113391020/205454399-955b8fd2-dca2-4b83-9395-4e8d745c468c.png)
4) Ожидался запрет на ввод в той области

**Comment by wmaksimova** [comment]
Исправили
