### ISSUE TITLE
В трекере нет ограничения ввода данных

### ISSUE THREAD

**Issue by vallerili** [wmaksimova/new_planner#4]
1) Открываю приложение
2) Хочу вручную поменять значения в трекере
3) Могу ввести любые символы и сколько угодно
![image](https://user-images.githubusercontent.com/113391020/205454570-cc5a477f-3e4f-4e79-a921-d40b89cf90c5.png)
4) Ожидались ограничения по символам и их количеству

**Comment by wmaksimova** [comment]
Исправили
