### ISSUE TITLE
Можно удалить и написать текст, где это не предусмотрено 

### ISSUE THREAD

**Issue by IrinaOsotova** [wmaksimova/new_planner#5]
1. Открываю приложение
2. Ставлю курсор на текст "Сколько дел запланировано на сегодня" или на текст "Твоя мотивация на день"
3. Нажимаю "Delete" на клавиатуре
4. Текст удаляется
![image](https://user-images.githubusercontent.com/113375568/205454880-c6a76109-cf65-40f8-9c11-bd118c39845b.png)
![image](https://user-images.githubusercontent.com/113375568/205454889-24a60588-abc0-48b2-9728-ac47c49394e3.png)
6. Ожидалось, что текст не будет удалён

**Comment by wmaksimova** [comment]
Исправили
