### ISSUE TITLE
Критическая ошибка трекера

### ISSUE THREAD

**Issue by IrinaOsotova** [wmaksimova/new_planner#6]
1. Открываю приложение
2. Удаляю цифры из трекера
![image](https://user-images.githubusercontent.com/113375568/205454968-92146cb4-1893-4103-92ff-1b9dbfcb53bc.png)
3. Нажимаю кнопку "сохранить"
4. Программа закрывается без предупреждений
5. Ожидалось предупреждение, что так нельзя сохранить

**Comment by wmaksimova** [comment]
Исправили
