### ISSUE TITLE
Ошибка в добавлении данных

### ISSUE THREAD

**Issue by IrinaOsotova** [wmaksimova/new_planner#7]
1. Открываю приложение
2. Ввожу несколько дел, которые хочу запланировать
3. Сохраняю их
![image](https://user-images.githubusercontent.com/113375568/205455383-bc69801b-aded-49be-a897-78a69a07789d.png)
4. Решаю, что хочу полностью поменять все запланированные дела в этот день
5. Меняю
![image](https://user-images.githubusercontent.com/113375568/205455411-a70a97e7-5b6b-4203-b0f4-5e4b407885da.png)
6. Нажимаю "сохранить"
7. Программа закрывается без предупреждений
8. Если я захочу в эту дату снова добавить дела, то это будет невозможно сделать. Программа будет закрываться снова и снова.
9. Ожидалось корректное сохранение

**Comment by wmaksimova** [comment]
Исправили
