### ISSUE TITLE
Слишком большой диапазон выбора дат

### ISSUE THREAD

**Issue by AnroMel** [wmaksimova/new_planner#8]
1. Запускаю приложение/планер 
2. Собираюсь выбрать дату
3. Нет ограничения по выбору дат, можно выбрать с 0001 года до 9999
![image](https://user-images.githubusercontent.com/113410483/205461817-f62fb774-11dc-462e-ba3d-554df5f61256.png)
![image](https://user-images.githubusercontent.com/113410483/205461820-cf9be466-cada-4106-9958-658799eea5f9.png)

**Comment by wmaksimova** [comment]
Исправили
