### ISSUE TITLE
В окошке можно написать отрицательное число, и при сохранении  или нажатии +/- программа вылетает

### ISSUE THREAD

**Issue by AnroMel** [wmaksimova/new_planner#9]
1. Запускаю приложение/планер 
2. Хочу уменьшить количество дел запланированных на сегодня
3. После нуля значения становятся отрицательными 
![image](https://user-images.githubusercontent.com/113410483/205461925-e23cb557-00db-4c9e-8884-3aa513b1f160.png)
4. После нажатия кнопки сохранить программа вылетает 
Ожидаемо:
ограничение от 0 до 7 на количество запланированных дел

**Comment by wmaksimova** [comment]
Исправили
